# use Ganache's forked mainnet mode as the default network
networks:
  default: development

autofetch_sources: true

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0
  - Uniswap/uniswap-v2-periphery@1.0.0-beta.0
  - Aave/protocol-v2@1.0.1

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"
      - "@uniswap=Uniswap/uniswap-v2-periphery@1.0.0-beta.0"
      - "@aave=Aave/protocol-v2@1.0.1"

reports:
  exclude_paths:
    - contracts/test/Token.sol
  exclude_contracts:
    - SafeMath
    - SafeERC20
    - Address
